hydra:
  run:
    dir: data/results/${sim.sim_dir}/${sim.sim_id}

sim:
  sim_dir: "run_1"
  sim_id: "1"
  
data:
  num_users: 2
  num_epochs: 5
  input_file: "data/input_text/conversation_data.json"
  output_file: "data/output_text/mytext4.json"
  method: "-c"
  train_eval_split: 0.8

model:
  model_name: "roneneldan/TinyStories-1M"
  tokenizer_name: "EleutherAI/gpt-neo-125M"

training:
  log_level: critical 
  do_train: True
  overwrite_output_dir: False
  max_steps: 10
  full_determinism: True